from __future__ import annotations

import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime
from typing import Any, Iterable

from config import settings


IS_POSTGRES = bool(settings.database_url)


@contextmanager
def get_connection():
    if IS_POSTGRES:
        import psycopg
        from psycopg.rows import dict_row

        conn = psycopg.connect(settings.database_url, row_factory=dict_row)
    else:
        conn = sqlite3.connect(settings.database_path)
        conn.row_factory = sqlite3.Row

    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def _execute(conn, query: str, params: Iterable[Any] | None = None):
    if IS_POSTGRES:
        query = query.replace("?", "%s")
    return conn.execute(query, tuple(params or ()))


def _row_get(row: Any, key: str, default: Any = None) -> Any:
    if row is None:
        return default
    if isinstance(row, dict):
        return row.get(key, default)
    try:
        return row[key]
    except (KeyError, IndexError, TypeError):
        return default


def init_db() -> None:
    if IS_POSTGRES:
        with get_connection() as conn:
            for statement in POSTGRES_SCHEMA:
                conn.execute(statement)
        return

    with get_connection() as conn:
        conn.executescript(SQLITE_SCHEMA)
        _ensure_sqlite_columns(conn)


def _ensure_sqlite_columns(conn) -> None:
    existing = {row["name"] for row in conn.execute("PRAGMA table_info(companies)").fetchall()}
    if "fax" not in existing:
        conn.execute("ALTER TABLE companies ADD COLUMN fax TEXT")
    if "latitude" not in existing:
        conn.execute("ALTER TABLE companies ADD COLUMN latitude REAL")
    if "longitude" not in existing:
        conn.execute("ALTER TABLE companies ADD COLUMN longitude REAL")


SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS companies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    url TEXT,
    industry TEXT,
    area TEXT,
    address TEXT,
    phone TEXT,
    fax TEXT,
    email TEXT,
    latitude REAL,
    longitude REAL,
    contact_url TEXT,
    summary TEXT,
    need_score INTEGER DEFAULT 0,
    score_reason TEXT,
    suggested_offer TEXT,
    status TEXT DEFAULT '未確認',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(name, url)
);

CREATE TABLE IF NOT EXISTS forms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INTEGER NOT NULL,
    form_url TEXT NOT NULL,
    fields_json TEXT DEFAULT '[]',
    has_captcha INTEGER DEFAULT 0,
    can_autofill INTEGER DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS proposals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INTEGER NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    version INTEGER DEFAULT 1,
    approved INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS activities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INTEGER NOT NULL,
    action_type TEXT NOT NULL,
    note TEXT,
    next_followup_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS send_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INTEGER NOT NULL,
    proposal_id INTEGER,
    channel TEXT NOT NULL,
    approach TEXT,
    subject TEXT,
    message TEXT,
    sent_at TEXT NOT NULL,
    note TEXT,
    FOREIGN KEY(company_id) REFERENCES companies(id),
    FOREIGN KEY(proposal_id) REFERENCES proposals(id)
);
"""


POSTGRES_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS companies (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        url TEXT,
        industry TEXT,
        area TEXT,
        address TEXT,
        phone TEXT,
        fax TEXT,
        email TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        contact_url TEXT,
        summary TEXT,
        need_score INTEGER DEFAULT 0,
        score_reason TEXT,
        suggested_offer TEXT,
        status TEXT DEFAULT '未確認',
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(name, url)
    )
    """,
    """
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS fax TEXT
    """,
    """
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION
    """,
    """
    ALTER TABLE companies ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION
    """,
    """
    CREATE TABLE IF NOT EXISTS forms (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
        form_url TEXT NOT NULL,
        fields_json TEXT DEFAULT '[]',
        has_captcha INTEGER DEFAULT 0,
        can_autofill INTEGER DEFAULT 0,
        notes TEXT,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS proposals (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
        subject TEXT,
        message TEXT NOT NULL,
        version INTEGER DEFAULT 1,
        approved INTEGER DEFAULT 0,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS activities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
        action_type TEXT NOT NULL,
        note TEXT,
        next_followup_at TEXT,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS send_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
        proposal_id BIGINT REFERENCES proposals(id) ON DELETE SET NULL,
        channel TEXT NOT NULL,
        approach TEXT,
        subject TEXT,
        message TEXT,
        sent_at TEXT NOT NULL,
        note TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status)",
    "CREATE INDEX IF NOT EXISTS idx_forms_company_id ON forms(company_id)",
    "CREATE INDEX IF NOT EXISTS idx_proposals_company_id ON proposals(company_id)",
    "CREATE INDEX IF NOT EXISTS idx_activities_company_id ON activities(company_id)",
    "CREATE INDEX IF NOT EXISTS idx_send_logs_company_id ON send_logs(company_id)",
    "CREATE INDEX IF NOT EXISTS idx_send_logs_sent_at ON send_logs(sent_at DESC)",
]


def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")


def upsert_companies(companies: Iterable[dict[str, Any]]) -> int:
    inserted_or_updated = 0
    with get_connection() as conn:
        for company in companies:
            timestamp = now_iso()
            _execute(
                conn,
                """
                INSERT INTO companies (
                    name, url, industry, area, address, phone, fax, email, latitude, longitude, contact_url,
                    summary, need_score, score_reason, suggested_offer, status,
                    created_at, updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, '未確認'), ?, ?)
                ON CONFLICT(name, url) DO UPDATE SET
                    industry=COALESCE(excluded.industry, companies.industry),
                    area=COALESCE(excluded.area, companies.area),
                    address=COALESCE(excluded.address, companies.address),
                    phone=COALESCE(excluded.phone, companies.phone),
                    fax=COALESCE(excluded.fax, companies.fax),
                    email=COALESCE(excluded.email, companies.email),
                    latitude=COALESCE(excluded.latitude, companies.latitude),
                    longitude=COALESCE(excluded.longitude, companies.longitude),
                    contact_url=COALESCE(excluded.contact_url, companies.contact_url),
                    summary=COALESCE(excluded.summary, companies.summary),
                    need_score=excluded.need_score,
                    score_reason=COALESCE(excluded.score_reason, companies.score_reason),
                    suggested_offer=COALESCE(excluded.suggested_offer, companies.suggested_offer),
                    updated_at=excluded.updated_at
                """,
                (
                    company.get("name"),
                    company.get("url"),
                    company.get("industry"),
                    company.get("area"),
                    company.get("address"),
                    company.get("phone"),
                    company.get("fax"),
                    company.get("email"),
                    company.get("latitude"),
                    company.get("longitude"),
                    company.get("contact_url"),
                    company.get("summary"),
                    int(company.get("need_score") or 0),
                    company.get("score_reason"),
                    company.get("suggested_offer"),
                    company.get("status"),
                    timestamp,
                    timestamp,
                ),
            )
            inserted_or_updated += 1
    return inserted_or_updated


def list_companies(status: str | None = None) -> list[Any]:
    with get_connection() as conn:
        if status and status != "すべて":
            return _execute(
                conn,
                "SELECT * FROM companies WHERE status = ? ORDER BY need_score DESC, updated_at DESC",
                (status,),
            ).fetchall()
        return _execute(
            conn,
            "SELECT * FROM companies ORDER BY need_score DESC, updated_at DESC",
        ).fetchall()


def get_company(company_id: int) -> Any | None:
    with get_connection() as conn:
        return _execute(conn, "SELECT * FROM companies WHERE id = ?", (company_id,)).fetchone()


def update_company_status(company_id: int, status: str) -> None:
    with get_connection() as conn:
        _execute(
            conn,
            "UPDATE companies SET status = ?, updated_at = ? WHERE id = ?",
            (status, now_iso(), company_id),
        )


def update_company_contact(
    company_id: int,
    email: str | None = None,
    contact_url: str | None = None,
    fax: str | None = None,
) -> None:
    fields = ["updated_at = ?"]
    values: list[Any] = [now_iso()]
    if email is not None:
        fields.insert(0, "email = NULLIF(?, '')")
        values.insert(0, email)
    if contact_url is not None:
        fields.insert(0, "contact_url = NULLIF(?, '')")
        values.insert(0, contact_url)
    if fax is not None:
        fields.insert(0, "fax = NULLIF(?, '')")
        values.insert(0, fax)

    values.append(company_id)
    with get_connection() as conn:
        _execute(conn, f"UPDATE companies SET {', '.join(fields)} WHERE id = ?", values)


def delete_company(company_id: int) -> None:
    with get_connection() as conn:
        _execute(conn, "DELETE FROM companies WHERE id = ?", (company_id,))


def delete_all_companies() -> None:
    with get_connection() as conn:
        _execute(conn, "DELETE FROM companies")


def delete_companies_by_url_patterns(patterns: list[str]) -> int:
    deleted = 0
    with get_connection() as conn:
        for pattern in patterns:
            rows = _execute(conn, "SELECT id FROM companies WHERE url LIKE ?", (pattern,)).fetchall()
            ids = [_row_get(row, "id") for row in rows]
            for company_id in ids:
                _execute(conn, "DELETE FROM companies WHERE id = ?", (company_id,))
                deleted += 1
    return deleted


def delete_companies_by_noise_patterns(url_patterns: list[str], text_patterns: list[str]) -> int:
    deleted_ids: set[int] = set()
    with get_connection() as conn:
        for pattern in url_patterns:
            rows = _execute(conn, "SELECT id FROM companies WHERE LOWER(COALESCE(url, '')) LIKE LOWER(?)", (pattern,)).fetchall()
            deleted_ids.update(int(_row_get(row, "id")) for row in rows)

        for pattern in text_patterns:
            rows = _execute(
                conn,
                """
                SELECT id FROM companies
                WHERE LOWER(COALESCE(name, '')) LIKE LOWER(?)
                   OR LOWER(COALESCE(summary, '')) LIKE LOWER(?)
                   OR LOWER(COALESCE(industry, '')) LIKE LOWER(?)
                   OR LOWER(COALESCE(url, '')) LIKE LOWER(?)
                """,
                (pattern, pattern, pattern, pattern),
            ).fetchall()
            deleted_ids.update(int(_row_get(row, "id")) for row in rows)

        for company_id in deleted_ids:
            _execute(conn, "DELETE FROM companies WHERE id = ?", (company_id,))
    return len(deleted_ids)


def add_proposal(company_id: int, subject: str, message: str) -> None:
    with get_connection() as conn:
        current = _execute(
            conn,
            "SELECT MAX(version) AS max_version FROM proposals WHERE company_id = ?",
            (company_id,),
        ).fetchone()
        version = int(_row_get(current, "max_version", 0) or 0) + 1
        _execute(
            conn,
            """
            INSERT INTO proposals (company_id, subject, message, version, created_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (company_id, subject, message, version, now_iso()),
        )


def list_proposals(company_id: int) -> list[Any]:
    with get_connection() as conn:
        return _execute(
            conn,
            "SELECT * FROM proposals WHERE company_id = ? ORDER BY version DESC",
            (company_id,),
        ).fetchall()


def add_form_result(
    company_id: int,
    form_url: str,
    fields: list[dict[str, Any]],
    has_captcha: bool,
    can_autofill: bool,
    notes: str = "",
) -> None:
    with get_connection() as conn:
        _execute(
            conn,
            """
            INSERT INTO forms (company_id, form_url, fields_json, has_captcha, can_autofill, notes, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                company_id,
                form_url,
                json.dumps(fields, ensure_ascii=False),
                int(has_captcha),
                int(can_autofill),
                notes,
                now_iso(),
            ),
        )


def list_forms(company_id: int) -> list[Any]:
    with get_connection() as conn:
        return _execute(
            conn,
            "SELECT * FROM forms WHERE company_id = ? ORDER BY created_at DESC",
            (company_id,),
        ).fetchall()


def add_activity(
    company_id: int,
    action_type: str,
    note: str,
    next_followup_at: str | None = None,
) -> None:
    with get_connection() as conn:
        _execute(
            conn,
            """
            INSERT INTO activities (company_id, action_type, note, next_followup_at, created_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (company_id, action_type, note, next_followup_at, now_iso()),
        )


def list_activities(company_id: int | None = None) -> list[Any]:
    with get_connection() as conn:
        if company_id:
            return _execute(
                conn,
                """
                SELECT a.*, c.name AS company_name
                FROM activities a
                JOIN companies c ON c.id = a.company_id
                WHERE company_id = ?
                ORDER BY a.created_at DESC
                """,
                (company_id,),
            ).fetchall()
        return _execute(
            conn,
            """
            SELECT a.*, c.name AS company_name
            FROM activities a
            JOIN companies c ON c.id = a.company_id
            ORDER BY a.created_at DESC
            """,
        ).fetchall()


def add_send_log(
    company_id: int,
    proposal_id: int | None,
    channel: str,
    approach: str,
    subject: str,
    message: str,
    note: str = "",
) -> None:
    with get_connection() as conn:
        _execute(
            conn,
            """
            INSERT INTO send_logs (
                company_id, proposal_id, channel, approach, subject, message, sent_at, note
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (company_id, proposal_id, channel, approach, subject, message, now_iso(), note),
        )


def list_send_logs(company_id: int | None = None) -> list[Any]:
    with get_connection() as conn:
        if company_id:
            return _execute(
                conn,
                """
                SELECT s.*, c.name AS company_name, c.url, c.contact_url, c.email, c.fax, c.status
                FROM send_logs s
                JOIN companies c ON c.id = s.company_id
                WHERE s.company_id = ?
                ORDER BY s.sent_at DESC
                """,
                (company_id,),
            ).fetchall()
        return _execute(
            conn,
            """
            SELECT s.*, c.name AS company_name, c.url, c.contact_url, c.email, c.fax, c.status
            FROM send_logs s
            JOIN companies c ON c.id = s.company_id
            ORDER BY s.sent_at DESC
            """,
        ).fetchall()


def send_count_by_company() -> dict[int, int]:
    with get_connection() as conn:
        rows = _execute(
            conn,
            """
            SELECT company_id, COUNT(*) AS send_count
            FROM send_logs
            GROUP BY company_id
            """,
        ).fetchall()
    return {int(_row_get(row, "company_id")): int(_row_get(row, "send_count")) for row in rows}
