CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT,
    industry TEXT,
    area TEXT,
    address TEXT,
    phone TEXT,
    fax TEXT,
    email TEXT,
    contact_url TEXT,
    summary TEXT,
    need_score INTEGER DEFAULT 0,
    score_reason TEXT,
    suggested_offer TEXT,
    status TEXT DEFAULT '未確認',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(name, url)
);

CREATE TABLE IF NOT EXISTS forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    form_url TEXT NOT NULL,
    fields_json TEXT DEFAULT '[]',
    has_captcha INTEGER DEFAULT 0,
    can_autofill INTEGER DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    subject TEXT,
    message TEXT NOT NULL,
    version INTEGER DEFAULT 1,
    approved INTEGER DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    note TEXT,
    next_followup_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS send_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    proposal_id BIGINT REFERENCES proposals(id) ON DELETE SET NULL,
    channel TEXT NOT NULL,
    approach TEXT,
    subject TEXT,
    message TEXT,
    sent_at TEXT NOT NULL,
    note TEXT
);

CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status);
CREATE INDEX IF NOT EXISTS idx_forms_company_id ON forms(company_id);
CREATE INDEX IF NOT EXISTS idx_proposals_company_id ON proposals(company_id);
CREATE INDEX IF NOT EXISTS idx_activities_company_id ON activities(company_id);
CREATE INDEX IF NOT EXISTS idx_send_logs_company_id ON send_logs(company_id);
CREATE INDEX IF NOT EXISTS idx_send_logs_sent_at ON send_logs(sent_at DESC);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS fax TEXT;
